
"use client"

import { Suspense, useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Search, ArrowUpRight, Filter, Play, Plus } from "lucide-react"
import { gsap } from "gsap"
import { CommunityGrid } from "@/components/community-grid"
import { UploadModal } from "@/components/upload-modal"

import { useAuth } from "@/context/auth-context"
import { useRouter } from "next/navigation"

function CommunityContent() {
  const headerRef = useRef<HTMLDivElement>(null)
  const [isUploadOpen, setIsUploadOpen] = useState(false)
  const { user } = useAuth()
  const router = useRouter()

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Elegant Header Fade
      gsap.from(".hero-text", {
        y: 40,
        opacity: 0,
        duration: 1.2,
        stagger: 0.15,
        ease: "power3.out"
      })

      // Controls Fade
      gsap.from(".hero-controls", {
        y: 20,
        opacity: 0,
        duration: 1,
        delay: 0.6,
        ease: "power2.out"
      })
    }, headerRef)

    return () => ctx.revert()
  }, [])

  return (
    <main ref={headerRef} className="min-h-screen bg-[#020202] text-white selection:bg-purple-500/30 overflow-x-hidden">

      {/* Upload Modal */}
      <UploadModal isOpen={isUploadOpen} onClose={() => setIsUploadOpen(false)} />

      {/* Sophisticated Ambient Background */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute top-[-20%] left-[20%] w-[60%] h-[60%] bg-purple-900/5 rounded-full blur-[180px]" />
        <div className="absolute bottom-[-10%] right-[-5%] w-[40%] h-[40%] bg-blue-900/5 rounded-full blur-[150px]" />
        <div className="absolute inset-0 bg-[url('/noise.png')] opacity-[0.02]" />
      </div>

      {/* Refined Header */}
      <section className="relative z-10 pt-28 pb-16 md:pt-40 md:pb-24 px-6 md:px-16 max-w-[2000px] mx-auto">
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-10 mb-20">
          <div className="space-y-6 max-w-3xl">
            <div className="flex items-center gap-3 hero-text">
              <div className="h-[1px] w-8 bg-purple-500/50"></div>
              <span className="text-xs font-medium tracking-[0.3em] uppercase text-neutral-400">The Gallery</span>
            </div>
            <h1 className="text-6xl md:text-8xl font-light tracking-tight text-white hero-text leading-[0.9]">
              Community <br />
              <span className="font-serif italic text-neutral-500">Perspectives</span>
            </h1>
            <p className="text-lg text-neutral-400 max-w-xl hero-text pt-4 leading-relaxed font-light">
              A curated exhibition of visual intelligence. Generated by imagination, powered by StudioX.
            </p>
          </div>

          <div className="hero-controls w-full lg:w-auto flex flex-col sm:flex-row gap-4 items-stretch sm:items-center">
            <Button
              className="h-14 rounded-full px-8 bg-white text-black hover:bg-neutral-200 transition-all duration-500 font-medium"
              onClick={() => {
                if (!user) {
                  router.push(`/login?redirect=${encodeURIComponent("/community")}`)
                  return
                }
                setIsUploadOpen(true)
              }}
            >
              <Plus className="h-4 w-4 mr-2" />
              Upload
            </Button>
            <div className="relative group w-full sm:w-[280px]">
              <Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-500 group-hover:text-white transition-colors duration-300" />
              <Input
                placeholder="Search the gallery..."
                className="pl-12 h-14 bg-white/[0.03] border-white/5 rounded-full text-base text-white placeholder:text-neutral-600 focus:bg-white/[0.08] focus:border-white/10 transition-all duration-500 shadow-xl"
              />
            </div>
            <Button variant="outline" size="icon" className="h-14 w-14 rounded-full border-white/5 bg-white/[0.03] hover:bg-white/[0.08] hover:text-white hover:border-white/10 transition-all duration-500">
              <Filter className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Masonry Layout via Component */}
        <CommunityGrid />

      </section>

      {/* Minimal Load More */}
      <section className="relative z-10 mx-auto max-w-7xl px-4 pb-32 text-center">
        <div className="h-[1px] w-full max-w-xs mx-auto bg-gradient-to-r from-transparent via-white/10 to-transparent mb-8"></div>
        <Button
          variant="ghost"
          size="lg"
          className="gap-3 text-neutral-500 hover:text-white hover:bg-transparent rounded-full px-8 h-auto text-sm tracking-widest uppercase transition-all duration-500 group"
        >
          View Archive
          <ArrowUpRight className="h-3 w-3 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
        </Button>
      </section>
    </main>
  )
}

export default function CommunityPage() {
  return (
    <Suspense fallback={null}>
      <CommunityContent />
    </Suspense>
  )
}
