import { CommunityPost } from "@/lib/types"

export const communityPosts: CommunityPost[] = [
    // ===== IMAGES =====
    {
        id: "ca-img-01",
        type: "image",
        title: "Cozy Christmas Café",
        description: "A pretty girl sitting in a warm, cozy Christmas café.",
        prompt: "Portrait of a beautiful young woman sitting in a cozy Christmas-themed café, warm ambient lighting, festive decorations, latte art on the table, bokeh lights in the background, soft cinematic color grading, photorealistic, 8k",
        author: { id: "user-ca-1", name: "Lily Chen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lily" },
        assetUrl: "/community_assets/ca-img-01.jpg",
        thumbnailUrl: "/community_assets/ca-img-01.jpg",
        aspectRatio: "portrait",
        likes: 2340,
        views: 9800,
        allowRemix: true,
        createdAt: new Date("2024-02-20"),
        tags: ["portrait", "christmas", "cozy"],
        model: "StudioX Flux Pro",
        preset: "Photorealistic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-02",
        type: "image",
        title: "Carefree Girl with Headphones",
        description: "A carefree girl listening to music at sunset.",
        prompt: "Candid lifestyle portrait of a carefree young woman wearing oversized headphones, listening to music at golden hour park, wind in hair, warm sunset backlight, joyful expression, shallow depth of field, photorealistic, 8k",
        author: { id: "user-ca-2", name: "Mia Torres", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia" },
        assetUrl: "/community_assets/ca-img-02.jpg",
        thumbnailUrl: "/community_assets/ca-img-02.jpg",
        aspectRatio: "portrait",
        likes: 1890,
        views: 7600,
        allowRemix: true,
        createdAt: new Date("2024-02-19"),
        tags: ["lifestyle", "music", "golden-hour"],
        model: "Midjourney v6",
        preset: "Cinematic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-03",
        type: "image",
        title: "Anime Blonde Warrior",
        description: "Cute anime-style blonde girl with a baseball bat.",
        prompt: "Cute anime style blonde girl holding a baseball bat, urban streetwear outfit, vibrant pop art background, bold outlines, cel-shaded lighting, dynamic pose, high detail manga illustration, 4k",
        author: { id: "user-ca-3", name: "Yuki Tanaka", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki" },
        assetUrl: "/community_assets/ca-img-03.jpg",
        thumbnailUrl: "/community_assets/ca-img-03.jpg",
        aspectRatio: "portrait",
        likes: 3210,
        views: 14500,
        allowRemix: true,
        createdAt: new Date("2024-02-18"),
        tags: ["anime", "character", "illustration"],
        model: "DALL·E 3",
        preset: "Artistic",
        quality: "4k",
        size: "1536x2048"
    },
    {
        id: "ca-img-04",
        type: "image",
        title: "Futuristic Woman on Cube",
        description: "A futuristic young woman sitting on a geometric cube.",
        prompt: "Futuristic young woman in sleek metallic outfit sitting on a glowing neon geometric cube, dark studio environment, dramatic rim lighting, cyberpunk aesthetic, reflective floor, hyper-detailed, photorealistic, 8k",
        author: { id: "user-ca-4", name: "Nova Sterling", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nova" },
        assetUrl: "/community_assets/ca-img-04.jpg",
        thumbnailUrl: "/community_assets/ca-img-04.jpg",
        aspectRatio: "portrait",
        likes: 2780,
        views: 11200,
        allowRemix: true,
        createdAt: new Date("2024-02-17"),
        tags: ["cyberpunk", "futuristic", "portrait"],
        model: "StudioX Flux Pro",
        preset: "Cinematic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-05",
        type: "image",
        title: "Glamour Fashion Editorial",
        description: "Stylish blonde in a shiny designer dress.",
        prompt: "High-fashion editorial portrait of a glamorous blonde woman wearing a shiny metallic couture dress, dramatic studio lighting, flowing hair, luxury beauty campaign style, ultra high resolution, photorealistic, 8k",
        author: { id: "user-ca-5", name: "Ava Laurent", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ava" },
        assetUrl: "/community_assets/ca-img-05.jpg",
        thumbnailUrl: "/community_assets/ca-img-05.jpg",
        aspectRatio: "portrait",
        likes: 4560,
        views: 19800,
        allowRemix: true,
        createdAt: new Date("2024-02-16"),
        tags: ["fashion", "glamour", "editorial"],
        model: "Midjourney v6",
        preset: "Photorealistic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-06",
        type: "image",
        title: "Happy Traveler",
        description: "Young woman enjoying travel in a sunny destination.",
        prompt: "Joyful young woman tourist enjoying a sunny Mediterranean town, straw hat, sundress, vibrant colorful buildings in background, natural daylight, candid travel photography style, warm tones, photorealistic, 8k",
        author: { id: "user-ca-6", name: "Emma Wanderlust", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma" },
        assetUrl: "/community_assets/ca-img-06.jpg",
        thumbnailUrl: "/community_assets/ca-img-06.jpg",
        aspectRatio: "portrait",
        likes: 1560,
        views: 6400,
        allowRemix: true,
        createdAt: new Date("2024-02-15"),
        tags: ["travel", "lifestyle", "sunny"],
        model: "StudioX Flux Pro",
        preset: "General",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-07",
        type: "image",
        title: "Joyful Radiant Smile",
        description: "Young woman with healthy skin laughing happily.",
        prompt: "Close-up beauty portrait of a joyful young woman with radiant healthy skin, natural makeup, genuine laugh, soft diffused studio lighting, clean white background, skincare campaign style, photorealistic, 8k",
        author: { id: "user-ca-7", name: "Sophie Bloom", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie" },
        assetUrl: "/community_assets/ca-img-07.jpg",
        thumbnailUrl: "/community_assets/ca-img-07.jpg",
        aspectRatio: "portrait",
        likes: 2100,
        views: 8900,
        allowRemix: true,
        createdAt: new Date("2024-02-14"),
        tags: ["beauty", "portrait", "natural"],
        model: "Midjourney v6",
        preset: "Photorealistic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-08",
        type: "image",
        title: "Winter City Portrait",
        description: "Portrait of a girl in a Christmas coat in the city.",
        prompt: "Cinematic winter portrait of a young woman wearing an elegant Christmas coat, snowy city street background, warm bokeh lights, gentle snowfall, moody atmospheric lighting, fashion photography style, photorealistic, 8k",
        author: { id: "user-ca-8", name: "Clara Snow", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Clara" },
        assetUrl: "/community_assets/ca-img-08.jpg",
        thumbnailUrl: "/community_assets/ca-img-08.jpg",
        aspectRatio: "portrait",
        likes: 3400,
        views: 13500,
        allowRemix: true,
        createdAt: new Date("2024-02-13"),
        tags: ["winter", "fashion", "cinematic"],
        model: "StudioX Flux Pro",
        preset: "Cinematic",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-09",
        type: "image",
        title: "Cozy Scarf Portrait",
        description: "Portrait of young woman wearing a checked scarf.",
        prompt: "Warm lifestyle portrait of a young woman wearing a cozy checked scarf, autumn setting, soft natural light filtering through trees, gentle smile, shallow depth of field, editorial style, photorealistic, 8k",
        author: { id: "user-ca-9", name: "Hazel Autumn", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hazel" },
        assetUrl: "/community_assets/ca-img-09.jpg",
        thumbnailUrl: "/community_assets/ca-img-09.jpg",
        aspectRatio: "portrait",
        likes: 980,
        views: 4200,
        allowRemix: true,
        createdAt: new Date("2024-02-12"),
        tags: ["autumn", "portrait", "cozy"],
        model: "Midjourney v6",
        preset: "General",
        quality: "8k",
        size: "1536x2048"
    },
    {
        id: "ca-img-10",
        type: "image",
        title: "AI Generated Artwork",
        description: "Stunning AI-generated visual concept.",
        prompt: "Abstract AI-generated digital artwork with flowing organic forms, vibrant iridescent colors, ethereal glowing particles, deep cosmic background, hyper-detailed textures, 8k resolution, octane render",
        author: { id: "user-ca-10", name: "Pixel Dreamz", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pixel" },
        assetUrl: "/community_assets/ca-img-10.jpg",
        thumbnailUrl: "/community_assets/ca-img-10.jpg",
        aspectRatio: "landscape",
        likes: 1240,
        views: 5100,
        allowRemix: true,
        createdAt: new Date("2024-02-11"),
        tags: ["ai-art", "abstract", "digital"],
        model: "StudioX Flux Pro",
        preset: "Artistic",
        quality: "8k",
        size: "2048x1536"
    },
    {
        id: "ca-img-11",
        type: "image",
        title: "Surreal Digital Vision",
        description: "A surreal AI-generated composition.",
        prompt: "Surreal dreamscape composition, floating geometric crystals over a calm reflective ocean at twilight, bioluminescent waves, ethereal sky gradient from deep purple to soft gold, highly detailed digital painting, 8k",
        author: { id: "user-ca-11", name: "Dreamcatcher", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dream" },
        assetUrl: "/community_assets/ca-img-11.png",
        thumbnailUrl: "/community_assets/ca-img-11.png",
        aspectRatio: "square",
        likes: 1670,
        views: 7200,
        allowRemix: true,
        createdAt: new Date("2024-02-10"),
        tags: ["surreal", "digital-art", "dreamscape"],
        model: "DALL·E 3",
        preset: "Artistic",
        quality: "4k",
        size: "1024x1024"
    },
    {
        id: "ca-img-12",
        type: "image",
        title: "Neural Art Composition",
        description: "Complex AI-generated neural artwork.",
        prompt: "Intricate neural network visualization artwork, interconnected glowing nodes in deep space, electric blue and magenta energy streams, macro detail of synaptic connections, cinematic composition, ultra high resolution, 8k",
        author: { id: "user-ca-12", name: "Synapse AI", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Synapse" },
        assetUrl: "/community_assets/ca-img-12.png",
        thumbnailUrl: "/community_assets/ca-img-12.png",
        aspectRatio: "landscape",
        likes: 890,
        views: 3800,
        allowRemix: true,
        createdAt: new Date("2024-02-09"),
        tags: ["neural", "ai-art", "abstract"],
        model: "StudioX Flux Pro",
        preset: "General",
        quality: "8k",
        size: "2048x1536"
    },
    {
        id: "ca-img-14",
        type: "image",
        title: "Ethereal Light Study",
        description: "Beautiful light and color exploration.",
        prompt: "Ethereal light study with prismatic refractions, soft volumetric rays passing through crystal formations, delicate color spectrum from warm amber to cool cerulean, minimalist composition, photorealistic render, 8k",
        author: { id: "user-ca-14", name: "Prism Studio", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Prism" },
        assetUrl: "/community_assets/ca-img-14.png",
        thumbnailUrl: "/community_assets/ca-img-14.png",
        aspectRatio: "landscape",
        likes: 1450,
        views: 6100,
        allowRemix: true,
        createdAt: new Date("2024-02-07"),
        tags: ["light", "abstract", "minimal"],
        model: "Midjourney v6",
        preset: "Artistic",
        quality: "8k",
        size: "2048x1536"
    },
    {
        id: "ca-img-15",
        type: "image",
        title: "Cinematic Concept Art",
        description: "A bold cinematic concept visualization.",
        prompt: "Epic cinematic concept art, grand scale sci-fi environment, towering alien architecture under dramatic storm clouds, volumetric god rays, hyper-detailed matte painting style, IMAX composition, 8k resolution",
        author: { id: "user-ca-15", name: "Cinescape", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cinescape" },
        assetUrl: "/community_assets/ca-img-15.png",
        thumbnailUrl: "/community_assets/ca-img-15.png",
        aspectRatio: "landscape",
        likes: 2890,
        views: 12400,
        allowRemix: true,
        createdAt: new Date("2024-02-06"),
        tags: ["scifi", "concept-art", "cinematic"],
        model: "StudioX Flux Pro",
        preset: "Cinematic",
        quality: "8k",
        size: "2048x1536"
    },

    // ===== VIDEOS =====
    {
        id: "ca-vid-01",
        type: "video",
        title: "Flowing Motion Study",
        description: "Mesmerizing flowing motion animation.",
        prompt: "Smooth cinematic motion study of flowing silk fabric in slow motion, warm golden lighting, ethereal particle effects, seamless loop, 4k 60fps, hyper-realistic render",
        author: { id: "user-ca-v1", name: "MotionLab", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Motion" },
        assetUrl: "/community_assets/ca-vid-01.mp4",
        thumbnailUrl: "/community_assets/ca-vid-01.mp4",
        aspectRatio: "landscape",
        likes: 3400,
        views: 15600,
        allowRemix: true,
        createdAt: new Date("2024-02-20"),
        tags: ["motion", "cinematic", "loop"],
        model: "Runway Gen-3 Alpha",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-02",
        type: "video",
        title: "Cinematic Scene Transition",
        description: "Beautiful seamless scene transition.",
        prompt: "Cinematic smooth camera transition through multiple dreamlike environments, morphing landscapes, volumetric fog, dramatic orchestral lighting, professional film grade, 4k",
        author: { id: "user-ca-v2", name: "TransitionFX", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TransFX" },
        assetUrl: "/community_assets/ca-vid-02.mp4",
        thumbnailUrl: "/community_assets/ca-vid-02.mp4",
        aspectRatio: "landscape",
        likes: 2100,
        views: 9800,
        allowRemix: true,
        createdAt: new Date("2024-02-19"),
        tags: ["transition", "cinematic", "seamless"],
        model: "Kling v2",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-03",
        type: "video",
        title: "Abstract Fluid Animation",
        description: "Mesmerizing abstract fluid dynamics.",
        prompt: "Abstract fluid dynamics simulation, swirling iridescent liquids mixing in slow motion, vivid neon colors against dark background, macro detail, seamless loop, cinematic 4k",
        author: { id: "user-ca-v3", name: "FluidVFX", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fluid" },
        assetUrl: "/community_assets/ca-vid-03.mp4",
        thumbnailUrl: "/community_assets/ca-vid-03.mp4",
        aspectRatio: "landscape",
        likes: 4500,
        views: 21000,
        allowRemix: true,
        createdAt: new Date("2024-02-18"),
        tags: ["abstract", "fluid", "animation"],
        model: "Runway Gen-3 Alpha",
        preset: "Artistic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-04",
        type: "video",
        title: "Ethereal Portrait Animation",
        description: "Portrait come to life with subtle motion.",
        prompt: "Subtle portrait animation, young woman with flowing hair in gentle breeze, eyes slowly opening, ethereal glowing particles floating around, cinematic shallow depth of field, 4k",
        author: { id: "user-ca-v4", name: "PortraitAI", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Portrait" },
        assetUrl: "/community_assets/ca-vid-04.mp4",
        thumbnailUrl: "/community_assets/ca-vid-04.mp4",
        aspectRatio: "portrait",
        likes: 5200,
        views: 24000,
        allowRemix: true,
        createdAt: new Date("2024-02-17"),
        tags: ["portrait", "animation", "ethereal"],
        model: "Kling v2",
        preset: "Cinematic",
        quality: "4k",
        size: "1080x1920"
    },
    {
        id: "ca-vid-05",
        type: "video",
        title: "Dynamic Scene Morph",
        description: "Seamless environment morphing sequence.",
        prompt: "Dynamic environment morphing sequence, urban cityscape transforming into lush tropical jungle, smooth camera push through, volumetric lighting changes, cinematic color grading, 4k 60fps",
        author: { id: "user-ca-v5", name: "MorphStudio", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Morph" },
        assetUrl: "/community_assets/ca-vid-05.mp4",
        thumbnailUrl: "/community_assets/ca-vid-05.mp4",
        aspectRatio: "landscape",
        likes: 1890,
        views: 8700,
        allowRemix: true,
        createdAt: new Date("2024-02-16"),
        tags: ["morph", "environment", "dynamic"],
        model: "Runway Gen-3 Alpha",
        preset: "General",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-06",
        type: "video",
        title: "Slow Motion Beauty",
        description: "Stunning slow motion beauty shot.",
        prompt: "Ultra slow motion beauty shot, woman turning head with flowing long hair, dramatic studio backlighting, particles catching light, 240fps cinematic quality, professional commercial grade, 4k",
        author: { id: "user-ca-v6", name: "SlowMo Lab", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SlowMo" },
        assetUrl: "/community_assets/ca-vid-06.mp4",
        thumbnailUrl: "/community_assets/ca-vid-06.mp4",
        aspectRatio: "landscape",
        likes: 2670,
        views: 11500,
        allowRemix: true,
        createdAt: new Date("2024-02-15"),
        tags: ["slowmo", "beauty", "cinematic"],
        model: "Kling v2",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-07",
        type: "video",
        title: "Neon Light Dance",
        description: "Vibrant neon light animation.",
        prompt: "Vibrant neon light dance animation, colorful light trails forming abstract patterns in darkness, synced to rhythmic pulsing, electric atmosphere, seamless loop, 4k",
        author: { id: "user-ca-v7", name: "NeonWave", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Neon" },
        assetUrl: "/community_assets/ca-vid-07.mp4",
        thumbnailUrl: "/community_assets/ca-vid-07.mp4",
        aspectRatio: "square",
        likes: 1340,
        views: 5900,
        allowRemix: true,
        createdAt: new Date("2024-02-14"),
        tags: ["neon", "animation", "abstract"],
        model: "Runway Gen-3 Alpha",
        preset: "Stylized",
        quality: "4k",
        size: "1080x1080"
    },
    {
        id: "ca-vid-08",
        type: "video",
        title: "Particle Burst",
        description: "Explosive particle effect animation.",
        prompt: "Explosive particle burst effect, millions of glowing particles erupting outward in slow motion, deep space background, vivid orange and cyan colors, physics simulation, cinematic 4k",
        author: { id: "user-ca-v8", name: "ParticleFX", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Particle" },
        assetUrl: "/community_assets/ca-vid-08.mp4",
        thumbnailUrl: "/community_assets/ca-vid-08.mp4",
        aspectRatio: "landscape",
        likes: 780,
        views: 3200,
        allowRemix: true,
        createdAt: new Date("2024-02-13"),
        tags: ["particles", "explosion", "vfx"],
        model: "Kling v2",
        preset: "General",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-09",
        type: "video",
        title: "Fashion Walk Sequence",
        description: "Cinematic fashion runway animation.",
        prompt: "Cinematic fashion runway sequence, elegant model walking in haute couture, dramatic spotlight, smoke effects, slow motion fabric movement, luxury brand commercial style, 4k",
        author: { id: "user-ca-v9", name: "FashionAI", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fashion" },
        assetUrl: "/community_assets/ca-vid-09.mp4",
        thumbnailUrl: "/community_assets/ca-vid-09.mp4",
        aspectRatio: "portrait",
        likes: 3100,
        views: 14200,
        allowRemix: true,
        createdAt: new Date("2024-02-12"),
        tags: ["fashion", "runway", "cinematic"],
        model: "Runway Gen-3 Alpha",
        preset: "Cinematic",
        quality: "4k",
        size: "1080x1920"
    },
    {
        id: "ca-vid-10",
        type: "video",
        title: "Micro Animation Loop",
        description: "Short mesmerizing micro loop.",
        prompt: "Short mesmerizing micro animation loop, single glowing orb pulsating with energy, ripple effects on a dark reflective surface, zen minimalist aesthetic, seamless loop, 4k",
        author: { id: "user-ca-v10", name: "MicroLoop", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Micro" },
        assetUrl: "/community_assets/ca-vid-10.mp4",
        thumbnailUrl: "/community_assets/ca-vid-10.mp4",
        aspectRatio: "square",
        likes: 560,
        views: 2400,
        allowRemix: true,
        createdAt: new Date("2024-02-11"),
        tags: ["loop", "minimal", "zen"],
        model: "Kling v2",
        preset: "Stylized",
        quality: "4k",
        size: "1080x1080"
    },
    {
        id: "ca-vid-11",
        type: "video",
        title: "Dramatic Reveal Shot",
        description: "Cinematic dramatic character reveal.",
        prompt: "Dramatic cinematic character reveal shot, silhouette slowly emerging from atmospheric fog, backlighting casting long shadows, epic orchestral mood, professional film grade, 4k",
        author: { id: "user-ca-v11", name: "CineReveal", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Reveal" },
        assetUrl: "/community_assets/ca-vid-11.mp4",
        thumbnailUrl: "/community_assets/ca-vid-11.mp4",
        aspectRatio: "landscape",
        likes: 2450,
        views: 10800,
        allowRemix: true,
        createdAt: new Date("2024-02-10"),
        tags: ["cinematic", "reveal", "dramatic"],
        model: "Runway Gen-3 Alpha",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-12",
        type: "video",
        title: "Color Gradient Flow",
        description: "Smooth flowing color gradient animation.",
        prompt: "Smooth flowing color gradient animation, liquid paint textures morphing between warm and cool palettes, soft diffused motion, abstract background loop, mesmerizing ambient, 4k",
        author: { id: "user-ca-v12", name: "GradientLab", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gradient" },
        assetUrl: "/community_assets/ca-vid-12.mp4",
        thumbnailUrl: "/community_assets/ca-vid-12.mp4",
        aspectRatio: "landscape",
        likes: 920,
        views: 4100,
        allowRemix: true,
        createdAt: new Date("2024-02-09"),
        tags: ["gradient", "abstract", "ambient"],
        model: "Kling v2",
        preset: "Artistic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-13",
        type: "video",
        title: "Epic Landscape Flyover",
        description: "Breathtaking aerial landscape sequence.",
        prompt: "Breathtaking aerial drone flyover of epic fantasy landscape, crystal-clear lake surrounded by snow-capped mountains, golden hour lighting, volumetric clouds, cinematic wide angle, National Geographic style, 4k",
        author: { id: "user-ca-v13", name: "SkyDrone", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SkyDrone" },
        assetUrl: "/community_assets/ca-vid-13.mp4",
        thumbnailUrl: "/community_assets/ca-vid-13.mp4",
        aspectRatio: "landscape",
        likes: 5600,
        views: 26000,
        allowRemix: true,
        createdAt: new Date("2024-02-08"),
        tags: ["landscape", "aerial", "epic"],
        model: "Runway Gen-3 Alpha",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-14",
        type: "video",
        title: "Glitch Art Sequence",
        description: "Digital glitch art motion graphics.",
        prompt: "Digital glitch art motion graphics, corrupted data visualization, pixelated fragments reassembling, vibrant RGB color channel separation, dark background, cyberpunk aesthetic, seamless loop, 4k",
        author: { id: "user-ca-v14", name: "GlitchCore", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Glitch" },
        assetUrl: "/community_assets/ca-vid-14.mp4",
        thumbnailUrl: "/community_assets/ca-vid-14.mp4",
        aspectRatio: "square",
        likes: 670,
        views: 2900,
        allowRemix: true,
        createdAt: new Date("2024-02-07"),
        tags: ["glitch", "cyberpunk", "motion"],
        model: "Kling v2",
        preset: "Stylized",
        quality: "4k",
        size: "1080x1080"
    },
    {
        id: "ca-vid-15",
        type: "video",
        title: "Liquid Metal Transform",
        description: "Chrome liquid metal morphing animation.",
        prompt: "Liquid chrome metal morphing animation, reflective mercury-like surface transforming into human face, dramatic studio lighting, high contrast, futuristic aesthetic, seamless loop, 4k",
        author: { id: "user-ca-v15", name: "ChromeVFX", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chrome" },
        assetUrl: "/community_assets/ca-vid-15.mp4",
        thumbnailUrl: "/community_assets/ca-vid-15.mp4",
        aspectRatio: "landscape",
        likes: 1230,
        views: 5400,
        allowRemix: true,
        createdAt: new Date("2024-02-06"),
        tags: ["metal", "morph", "futuristic"],
        model: "Runway Gen-3 Alpha",
        preset: "General",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-16",
        type: "video",
        title: "Cinematic Character Walk",
        description: "Professional character animation clip.",
        prompt: "Professional cinematic character walk cycle, stylish protagonist walking through neon-lit alleyway, rain-slicked pavement reflections, moody atmospheric fog, film noir style, 4k 24fps",
        author: { id: "user-ca-v16", name: "CharAnimFX", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=CharAnim" },
        assetUrl: "/community_assets/ca-vid-16.mp4",
        thumbnailUrl: "/community_assets/ca-vid-16.mp4",
        aspectRatio: "landscape",
        likes: 3800,
        views: 17400,
        allowRemix: true,
        createdAt: new Date("2024-02-05"),
        tags: ["character", "cinematic", "noir"],
        model: "Kling v2",
        preset: "Cinematic",
        quality: "4k",
        size: "1920x1080"
    },
    {
        id: "ca-vid-17",
        type: "video",
        title: "Quick Motion Clip",
        description: "Short dynamic motion design clip.",
        prompt: "Quick dynamic motion design clip, bold typography animation with kinetic energy, minimalist black and white palette with accent color pop, professional broadcast style, 4k",
        author: { id: "user-ca-v17", name: "QuickMotion", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Quick" },
        assetUrl: "/community_assets/ca-vid-17.mp4",
        thumbnailUrl: "/community_assets/ca-vid-17.mp4",
        aspectRatio: "landscape",
        likes: 340,
        views: 1500,
        allowRemix: true,
        createdAt: new Date("2024-02-04"),
        tags: ["motion-design", "typography", "minimal"],
        model: "Runway Gen-3 Alpha",
        preset: "Stylized",
        quality: "4k",
        size: "1920x1080"
    },
]
